from bs4 import BeautifulSoup
import requests
import re


# Get list of markets
def markets():
    url = 'https://www.ingsprinters.nl/sprinters/'

    r = requests.get(url)
    if r.status_code == 200:
        payload = []
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find("div", class_="grid grid--wrap grid--align-start")
        names = data.find_all("a", class_="list-group__label")

        # To return a list
        for x in range(0, len(names)):
            payload.append(names[x].get_text().strip().replace("é", "e"))

        file = open("markets.txt", "w")
        file.write(str(payload))
        return payload

    else:
        return None


# Get market info
def market_info(market):
    market = market.replace('(', '')
    market = market.replace(')', '')
    market = market.replace(' ', '-')

    url = 'https://www.ingsprinters.nl/sprinters/' + market

    r = requests.get(url)
    if r.status_code == 200:
        payload = {}
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find("div", class_="card__body")
        key = data.find("h2", class_="h4 no-margin").text.strip()
        value = data.find_all("span")

        payload[key.replace("*", "")] = value[0].text.strip() + ' ' + value[1].text.strip()

        return payload

    else:
        return None


# Get list of current long and short sprinters from a certain market
# Expects a string (generated by markets()) that contains Long or Short (added to the string) at the end
def sprinter_list(sprinter):
    sprinter = sprinter.replace('(', '')
    sprinter = sprinter.replace(')', '')
    query = sprinter.split()

    url = 'https://www.ingsprinters.nl/markten/indices/' + '-'.join(query[:-1])

    r = requests.get(url)
    if r.status_code == 200:
        payload = {}
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find_all("a", class_="fill-cell font-narrow tick__text")
        for item in data:
            if query[-1].capitalize() in item.get_text():
                payload[item.get_text()] = re.sub(r'.*/NL', 'NL', item.get('href'))

        return payload

    else:
        return None


# Get data from the sprinter
# Expects sprinter name and ISIN (generated by sprinter_list())
def sprinter_info(sprinter, ISIN):
    sprinter = sprinter.replace('(', '')
    sprinter = sprinter.replace(')', '')
    sprinter = sprinter.replace(' ', '-')

    url = 'https://www.ingsprinters.nl/markten/indices/' + sprinter + '/' + ISIN

    r = requests.get(url)
    if r.status_code == 200:
        payload = {}
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find("div", class_="meta-block__row")

        for key, value in payload.items():
            print(key, value.text.strip())

        name = data.find_all("h3", class_="meta__heading no-margin")
        date = data.find_all("span", class_=lambda x: x and x.startswith(
            'meta__value meta__value--l'))

        for x in range(len(name)):
            if x < (len(name) - 1):
                payload[name[x].text.strip()] = date[x].text.strip()
            else:
                payload[name[x].text.strip().replace("*", "")] = [date[x].text.strip(), date[6].text.strip()]

        return payload

    else:
        return None


def test_functions():
    sprinter = "AEX Short"
    ISIN = "NL0012065692"

    print(markets())
    print(sprinter_list(sprinter))
    print(sprinter_info(sprinter, ISIN))
