from bs4 import BeautifulSoup
import requests
import re


# Get list of markets
def markets():
    url = 'https://www.ingsprinters.nl/sprinters/'

    r = requests.get(url)
    if r.status_code == 200:
        payload = []
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find("div", class_="grid grid--wrap grid--align-start")
        names = data.find_all("a", class_="list-group__label")

        # To return a list
        for x in range(0, len(names)):
            payload.append(names[x].get_text().strip().replace("é", "e"))

        file = open("markets.txt", "w")
        file.write(str(payload))
        return payload

    else:
        return None


# Get market info
def market_info(market):
    market = market.replace('(', '')
    market = market.replace(')', '')
    market = market.replace(' ', '-')

    url = 'https://www.ingsprinters.nl/sprinters/' + market

    r = requests.get(url)
    if r.status_code == 200:
        payload = {}
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find("div", class_="card__body")
        key = data.find("h2", class_="h4 no-margin").text.strip()
        value = data.find_all("span")

        payload[key.replace("*", "")] = value[0].text.strip() + ' ' + value[1].text.strip()

        return payload

    else:
        return None


# Get list of current long and short sprinters from a certain market
# Expects a string (generated by markets()) that contains Long or Short (added to the string) at the end
def sprinter_list(sprinter):
    sprinter = sprinter.replace('(', '')
    sprinter = sprinter.replace(')', '')
    query = sprinter.split()

    url = 'https://www.ingsprinters.nl/markten/indices/' + '-'.join(query[:-1])

    r = requests.get(url)
    if r.status_code == 200:
        payload = {}
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find_all("a", class_="fill-cell font-narrow tick__text")
        for item in data:
            if query[-1].capitalize() in item.get_text():
                payload[item.get_text()] = re.sub(r'.*/NL', 'NL', item.get('href'))

        return payload

    else:
        return None


# Get data from the sprinter
# Expects sprinter name and ISIN (generated by sprinter_list())
def sprinter_info(sprinter, ISIN):
    sprinter = sprinter.replace('(', '')
    sprinter = sprinter.replace(')', '')
    sprinter = sprinter.replace(' ', '-')

    url = 'https://www.ingsprinters.nl/markten/indices/' + sprinter + '/' + ISIN

    r = requests.get(url)
    if r.status_code == 200:
        payload = {}
        soup = BeautifulSoup(r.content, "html.parser")

        data = soup.find("div", class_="meta-block__row")

        for key, value in payload.items():
            print(key, value.text.strip())

        name = data.find_all("h3", class_="meta__heading no-margin")
        date = data.find_all("span", class_=lambda x: x and x.startswith(
            'meta__value meta__value--l'))

        for x in range(len(name)):
            if x < (len(name) - 1):
                payload[name[x].text.strip()] = date[x].text.strip()
            else:
                payload[name[x].text.strip().replace("*", "")] = [date[x].text.strip(), date[6].text.strip()]

        return payload

    else:
        return None


# Add market/sprinter to database
def add(user_id, query):
    if query:
        if query.split()[-1].startswith("NL"):
            ISIN = query.split()[-1]
            query = "".join(query.split()[:-1])
        else:
            ISIN = ''

        with open('database.pkl', 'rb') as file:
            try:
                data = pickle.load(file)
            except EOFError:
                data = {}

        with open('database.pkl', 'wb') as file:
            if user_id not in data.keys():  # Add user
                data[user_id] = {}

            if query not in data[user_id]:  # Add market
                data[user_id][query] = []
                message = "Market added!"
            elif query in data[user_id]:
                message = "Market already added!"

            if ISIN and ISIN not in data[user_id][query]:  # Add ISIN to market
                data[user_id][query].append(ISIN)
                message = "Sprinter added!"
            elif ISIN and ISIN in data[user_id][query]:
                message = "Sprinter already added!"

            pickle.dump(data, file)

    else:
        message = "Add a market with `/add market` or a sprinter with `/add market sprinter`"

    return message


# Remove market/sprinter from database
def remove(user_id, query):
    if query:
        if query.split()[-1].startswith("NL"):
            ISIN = query.split()[-1]
            query = "".join(query.split()[:-1])
        else:
            ISIN = ''

        with open('database.pkl', 'rb') as file:
            try:
                data = pickle.load(file)
            except EOFError:
                data = {}

        with open('database.pkl', 'wb') as file:
            if user_id not in data.keys():
                message = "You're not in the database!"

            else:  # User in database
                if ISIN and ISIN in data[user_id][query]:  # Remove ISIN
                    data[user_id][query].remove(ISIN)
                    message = "Sprinter removed!"
                elif ISIN and ISIN not in data[user_id][query]:
                    message = "Sprinter is not in your favorites!"

                if (query in data[user_id].keys()) and not ISIN:  # Remove market
                    data[user_id].pop(query, None)
                    message = "Market removed!"
                elif (query not in data[user_id].keys()):
                    message = "Market is not in your favorites!"

                if query.lower() == 'me':
                    data.pop(user_id, None)
                    message = "User removed!"

                logging.info(data)
                pickle.dump(data, file)

    else:
        message = "Remove a market with `/remove market` or a sprinter with `/remove market sprinter`"

    return message


def test_functions():
    sprinter = "AEX Short"
    ISIN = "NL0012065692"

    print(markets())
    print(sprinter_list(sprinter))
    print(sprinter_info(sprinter, ISIN))
